I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 156, in script
    if kfc_with_pasha :
  File "game/script.rpy", line 156, in <module>
    if kfc_with_pasha :
NameError: name 'kfc_with_pasha' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 156, in script
    if kfc_with_pasha :
  File "C:\renpy-8.0.3-sdk\renpy\ast.py", line 2115, in execute
    if renpy.python.py_eval(condition):
  File "C:\renpy-8.0.3-sdk\renpy\python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 156, in <module>
    if kfc_with_pasha :
NameError: name 'kfc_with_pasha' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
TechTales 1.0
Sat Mar 11 02:37:10 2023
