I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 162, in script
    $ go_or_no = true
  File "game/script.rpy", line 162, in <module>
    $ go_or_no = true
NameError: name 'true' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 162, in script
    $ go_or_no = true
  File "C:\renpy-8.0.3-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\renpy-8.0.3-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 162, in <module>
    $ go_or_no = true
NameError: name 'true' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
TechTales 1.0
Sat Mar 11 02:30:43 2023
