I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 835, in script
    scene rain yuli yuli
Exception: Image 'rain yuli' does not accept attributes 'yuli'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 835, in script
    scene rain yuli yuli
  File "X:\Download\RenPy\renpy-8.0.3-sdk\renpy\ast.py", line 1542, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "X:\Download\RenPy\renpy-8.0.3-sdk\renpy\ast.py", line 1371, in show_imspec
    renpy.config.show(name,
  File "X:\Download\RenPy\renpy-8.0.3-sdk\renpy\exports.py", line 686, in show
    if not base.find_target() and renpy.config.missing_show:
  File "X:\Download\RenPy\renpy-8.0.3-sdk\renpy\display\image.py", line 414, in find_target
    self.target = target._duplicate(a)
  File "X:\Download\RenPy\renpy-8.0.3-sdk\renpy\display\core.py", line 397, in _duplicate
    args.extraneous()
  File "X:\Download\RenPy\renpy-8.0.3-sdk\renpy\display\core.py", line 265, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'rain yuli' does not accept attributes 'yuli'.

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
Любовь, выпивка, паника, лирика 1.0
Thu Mar 23 00:48:37 2023
