I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 3263, in script
    "К кому бы мне подсесть?"
  File "game/script.rpy", line 3263, in script
    "К кому бы мне подсесть?"
  File "renpy/common/00gamemenu.rpy", line 126, in _invoke_game_menu
    renpy.call_in_new_context('_game_menu')
  File "renpy/common/00action_file.rpy", line 463, in __call__
    renpy.load(fn)
Exception: Couldn't find a place to stop rolling back. Perhaps the script changed in an incompatible way?

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\renpy-8.0.3-sdk\renpy\bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "D:\renpy-8.0.3-sdk\renpy\main.py", line 660, in main
    run(restart)
  File "D:\renpy-8.0.3-sdk\renpy\main.py", line 146, in run
    renpy.execution.run_context(True)
  File "D:\renpy-8.0.3-sdk\renpy\execution.py", line 938, in run_context
    context.run()
  File "game/script.rpy", line 3263, in script
    "К кому бы мне подсесть?"
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 441, in raise_
  File "game/script.rpy", line 3263, in script
    "К кому бы мне подсесть?"
  File "D:\renpy-8.0.3-sdk\renpy\ast.py", line 921, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "D:\renpy-8.0.3-sdk\renpy\exports.py", line 1373, in say
    who(what, *args, **kwargs)
  File "D:\renpy-8.0.3-sdk\renpy\character.py", line 1266, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "D:\renpy-8.0.3-sdk\renpy\character.py", line 927, in do_display
    display_say(who,
  File "D:\renpy-8.0.3-sdk\renpy\character.py", line 666, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "D:\renpy-8.0.3-sdk\renpy\ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "D:\renpy-8.0.3-sdk\renpy\display\core.py", line 3377, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "D:\renpy-8.0.3-sdk\renpy\display\core.py", line 4258, in interact_core
    rv = root_widget.event(ev, x, y, 0)
  File "D:\renpy-8.0.3-sdk\renpy\display\layout.py", line 1175, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "D:\renpy-8.0.3-sdk\renpy\display\behavior.py", line 478, in event
    rv = run(action)
  File "D:\renpy-8.0.3-sdk\renpy\display\behavior.py", line 329, in run
    return action(*args, **kwargs)
  File "renpy/common/00gamemenu.rpy", line 126, in _invoke_game_menu
    renpy.call_in_new_context('_game_menu')
  File "D:\renpy-8.0.3-sdk\renpy\game.py", line 346, in call_in_new_context
    return renpy.execution.run_context(False)
  File "D:\renpy-8.0.3-sdk\renpy\execution.py", line 938, in run_context
    context.run()
  File "renpy/common/_layout/screen_load_save.rpym", line 35, in script
    $ ui.interact()
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 441, in raise_
  File "renpy/common/_layout/screen_load_save.rpym", line 35, in script
    $ ui.interact()
  File "D:\renpy-8.0.3-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\renpy-8.0.3-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/_layout/screen_load_save.rpym", line 35, in <module>
    $ ui.interact()
  File "D:\renpy-8.0.3-sdk\renpy\ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "D:\renpy-8.0.3-sdk\renpy\display\core.py", line 3377, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "D:\renpy-8.0.3-sdk\renpy\display\core.py", line 4258, in interact_core
    rv = root_widget.event(ev, x, y, 0)
  File "D:\renpy-8.0.3-sdk\renpy\display\layout.py", line 1175, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "D:\renpy-8.0.3-sdk\renpy\display\transition.py", line 53, in event
    return self.new_widget.event(ev, x, y, st) # E1101
  File "D:\renpy-8.0.3-sdk\renpy\display\layout.py", line 1175, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "D:\renpy-8.0.3-sdk\renpy\display\layout.py", line 1175, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "D:\renpy-8.0.3-sdk\renpy\display\screen.py", line 743, in event
    rv = self.child.event(ev, x, y, st)
  File "D:\renpy-8.0.3-sdk\renpy\display\layout.py", line 1175, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "D:\renpy-8.0.3-sdk\renpy\display\layout.py", line 1399, in event
    rv = super(Window, self).event(ev, x, y, st)
  File "D:\renpy-8.0.3-sdk\renpy\display\layout.py", line 279, in event
    rv = d.event(ev, x - xo, y - yo, st)
  File "D:\renpy-8.0.3-sdk\renpy\display\layout.py", line 1175, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "D:\renpy-8.0.3-sdk\renpy\display\layout.py", line 1175, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "D:\renpy-8.0.3-sdk\renpy\display\behavior.py", line 1073, in event
    return handle_click(self.clicked)
  File "D:\renpy-8.0.3-sdk\renpy\display\behavior.py", line 1008, in handle_click
    rv = run(action)
  File "D:\renpy-8.0.3-sdk\renpy\display\behavior.py", line 322, in run
    new_rv = run(i, *args, **kwargs)
  File "D:\renpy-8.0.3-sdk\renpy\display\behavior.py", line 329, in run
    return action(*args, **kwargs)
  File "renpy/common/00action_file.rpy", line 463, in __call__
    renpy.load(fn)
  File "D:\renpy-8.0.3-sdk\renpy\loadsave.py", line 769, in load
    log.unfreeze(roots, label="_after_load")
  File "D:\renpy-8.0.3-sdk\renpy\rollback.py", line 1078, in unfreeze
    self.rollback(0, force=True, label=label, greedy=greedy, on_load=True)
  File "D:\renpy-8.0.3-sdk\renpy\rollback.py", line 889, in rollback
    self.load_failed()
  File "D:\renpy-8.0.3-sdk\renpy\rollback.py", line 807, in load_failed
    raise Exception("Couldn't find a place to stop rolling back. Perhaps the script changed in an incompatible way?")
Exception: Couldn't find a place to stop rolling back. Perhaps the script changed in an incompatible way?

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
Любовь, выпивка, паника, лирика 1.0
Fri Mar 24 16:14:53 2023
