I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 2706, in script
    with disslove
  File "game/script.rpy", line 2706, in <module>
    with disslove
NameError: name 'disslove' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 2706, in script
    with disslove
  File "C:\renpy-8.0.3-sdk\renpy\ast.py", line 1651, in execute
    trans = renpy.python.py_eval(self.expr)
  File "C:\renpy-8.0.3-sdk\renpy\python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 2706, in <module>
    with disslove
NameError: name 'disslove' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
Любовь, выпивка, паника, лирика 1.0
Wed Mar 22 00:00:11 2023
